kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pipeline-pvc  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Pending
