apiVersion: tekton.dev/v1beta1
kind: Task
metadata:  
  name: curl-task  
spec:
  params:
    - name: appName
      type: string
  steps:
    - image: >-
        docker.io/curlimages/curl:7.72.0@sha256:bd5bbd35f89b867c1dccbc84b8be52f3f74dea20b46c5fe0db3780e040afcb6f
      name: ''
      resources: {}
      script: >

        CI_PROJECT_ID="23275515" 

        SOURCE_BRANCH="developer"

        TARGET_BRANCH="stage"

        PRIVATE_TOKEN="glpat-LppyTdboVx5zJXqM784g"

        ASSIGNEE="iam-roger-io"

        BODY="{
            \"id\": $CI_PROJECT_ID,
            \"source_branch\": \"$SOURCE_BRANCH\",
            \"target_branch\": \"$TARGET_BRANCH\",
            \"remove_source_branch\": false,
            \"title\": \"TEKTON: MERGE REQUEST\",
            \"assignee\": {
            \"username\": \"$ASSIGNEE\"
          }
        }"

        echo "Merge Request Body: " $BODY 

        echo "Merge Request PRIVATE_TOKEN: "$PRIVATE_TOKEN

        echo "curl -X
        POST'https://gitlab.com/api/v4/projects/23275515/merge_requests'
        --header 'PRIVATE-TOKEN:$PRIVATE_TOKEN' --header 'Content-Type:
        application/json' --data '${BODY}'" 

        echo "Merge Request criado"
  workspaces:
    - name: source
