apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-gitops
spec:
  params:
    - name: GITOPS_REPOSITORY_URL
      type: string
    - name: GITOPS_BRANCH
      type: string
    - name: GITOPS_GLOBAL_USER_EMAIL
      type: string               
    - name: GITOPS_GLOBAL_USER_NAME
      type: string                     
  steps:
    - image: >-
        docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
      name: 'git-clone-gitops'
      resources: {}
      script: >

        rm -rfv /workspace/source/demo-integration-gitops

        cd /workspace/source

        git config --global user.email "$(params.GITOPS_GLOBAL_USER_EMAIL)"

        git config  --global user.name "$(params.GITOPS_GLOBAL_USER_NAME)"

        git clone $(params.GITOPS_REPOSITORY_URL)  -b $(params.GITOPS_BRANCH) 
        

  workspaces:
    - name: source
