apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata: 
  name: event-listener-bi8yt8
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: gitlab-push
      template:
        ref: trigger-template-pipeline-demo-dmfmn2