kind: Secret
apiVersion: v1
metadata:
  name: gitlab-credentials  
  annotations:
    tekton.dev/git-0: 'https://gitlab.com'
data:
  password: <INSERT YOUR PASSWORD>
  username: <INSERT YOUR USERNAME>
type: kubernetes.io/basic-auth
