kind: Secret
apiVersion: v1
metadata:
  name: redhat-registry-credentials
  annotations:
    tekton.dev/docker-0: 'https://registry.redhat.io'
data:
  .dockerconfigjson: >-
    <JSON CONTENT>
type: kubernetes.io/dockerconfigjson
